export const analyticsAdminCopy = {
  title: "Web Analytics",
  trafficErrorLog: "Web Analytics traffic report failed",
  businessErrorLog: "Web Analytics business report failed",
  engagementErrorLog: "Web Analytics engagement report failed",
  kicker: "Interner GoStone-Bericht",
  intro: "Verkehr, Registrierungen und Spielaktivität in einer geschützten Übersicht.",
  generated: "Stand",
  protected: "Nicht verlinkt · HTTP-geschützt · nicht indexierbar",
  privacyTitle: "Datenschutzgrenze",
  privacyText: "Vercel stellt Orts- und Gerätedaten ausschließlich anonym und aggregiert bereit. Deshalb kann diese Übersicht Länder, Seiten und Geräte sowie getrennt davon GoStone-Konten und Partien zeigen, aber kein Land einer bestimmten Person oder einem bestimmten Konto zuordnen.",
  traffic: "Besucher und Seitenaufrufe",
  trafficWindow: "Produktionsdaten im gewählten Zeitraum (UTC). Gesamtwerte seit Aktivierung von Vercel Web Analytics.",
  period: "Zeitraum",
  refresh: "Aktualisieren",
  today: "Heute",
  day: "Tag",
  days: "Tage",
  trend: "Verlauf",
  periodVisitors: "Besucher im Zeitraum",
  periodPageviews: "Seitenaufrufe im Zeitraum",
  viewsPerVisitor: "Aufrufe pro Besucher",
  routes: "Routen",
  share: "Anteil der Aufrufe",
  visitorsNote: "Vercel erkennt Besucher mit einem täglich erneuerten Hash. Besucher sind keine dauerhaft eindeutigen Personen und keine Sitzungen. Aufrufe pro Besucher sind keine Seiten pro Sitzung.",
  engagement: "Aufenthaltszeit",
  averageTime: "Ø sichtbare Zeit pro Seitenaufruf",
  visibleTime: "Sichtbare Zeit insgesamt",
  measuredViews: "Gemessene Seitenaufrufe",
  engagementNote: "Eigene Messung ab diesem Deployment, ohne Cookies oder Besucherkennungen. Gezählt wird die Zeit in sichtbaren Tabs, auch während einer Partie. Meldung alle 30 Sekunden sowie beim Verlassen oder Ausblenden. Keine vollständige Sitzungsdauer; blockierte, verlorene oder noch ausstehende Meldungen können die Werte beeinflussen. Die Aufrufzahlen können von Vercel abweichen.",
  trafficUnavailable: "Vercel-Daten konnten nicht geladen werden. Web Analytics muss im Projekt aktiviert sein und WEB_ANALYTICS_VERCEL_TOKEN, WEB_ANALYTICS_PROJECT_ID sowie WEB_ANALYTICS_TEAM_ID müssen auf dem Server eingerichtet sein. Auch Tariflimits oder ein abgelaufener Token können den Abruf verhindern.",
  vercelLimitations: "Weitere Vercel-Auswertungen: UTM-Kampagnen benötigen Web Analytics Plus, eigene Events Pro oder Enterprise. Suchparameter werden hier aus Datenschutzgründen entfernt. Sitzungsdauer und Absprungrate liefert die öffentliche Web-Analytics-API nicht.",
  business: "Konten und Spielbetrieb",
  businessWindow: "Live aus der GoStone-Datenbank; Zeitfenster werden jeweils bis heute berechnet.",
  totalVisitors: "Besucher gesamt",
  totalPageviews: "Seitenaufrufe gesamt",
  accountsTotal: "Konten gesamt",
  accountsToday: "Neue Konten heute",
  accounts7d: "Neue Konten · 7 Tage",
  accounts30d: "Neue Konten · 30 Tage",
  gamesTotal: "Partien gesamt",
  gamesToday: "Neue Partien heute",
  games7d: "Neue Partien · 7 Tage",
  games30d: "Neue Partien · 30 Tage",
  activeGames: "Aktive Partien",
  finishedGames: "Beendete Partien",
  movesTotal: "Gespielte Züge gesamt",
  trafficTrend: "Verlauf · 30 Tage",
  businessTrend: "Registrierungen und Partien · 30 Tage",
  countries: "Länder",
  pages: "Seiten",
  referrers: "Herkunft",
  devices: "Geräte",
  browsers: "Browser",
  operatingSystems: "Betriebssysteme",
  recentAccounts: "Neueste Konten",
  recentGames: "Neueste Partien",
  breakdown30d: "Partie-Aufteilung · 30 Tage",
  boardSizes: "Brettgrößen",
  timeControls: "Zeitmodi",
  gameTypes: "Partiearten",
  rules: "Regeln",
  visitors: "Besucher",
  pageviews: "Aufrufe",
  date: "Datum",
  registrations: "Konten",
  games: "Partien",
  finished: "Beendet",
  account: "Konto",
  created: "Erstellt",
  lastGame: "Letzte Partie",
  players: "Spieler",
  details: "Details",
  moves: "Züge",
  status: "Status",
  noData: "Noch keine Daten in diesem Zeitraum.",
  unavailable: "Dieser Datenbereich ist vorübergehend nicht verfügbar.",
  never: "Noch keine",
  active: "Aktiv",
  complete: "Beendet",
  black: "Schwarz",
  white: "Weiß",
  versus: "gegen",
} as const;
