export const analyticsAdminCopy = {
  title: "Web Analytics",
  trafficErrorLog: "Web Analytics traffic report failed",
  businessErrorLog: "Web Analytics business report failed",
  engagementErrorLog: "Web Analytics engagement report failed",
  reviewErrorLog: "Web Analytics review report failed",
  surveyErrorLog: "Web Analytics price survey report failed",
  kicker: "Interner GoStone-Bericht",
  intro: "Verkehr, Registrierungen und Spielaktivität in einer geschützten Übersicht.",
  generated: "Stand",
  protected: "Nicht verlinkt · HTTP-geschützt · nicht indexierbar",
  privacyTitle: "Datenschutzgrenze",
  privacyText: "Vercel stellt Orts- und Gerätedaten ausschließlich anonym und aggregiert bereit. Deshalb kann diese Übersicht Länder, Seiten und Geräte sowie getrennt davon GoStone-Konten und Partien zeigen, aber kein Land einer bestimmten Person oder einem bestimmten Konto zuordnen.",
  traffic: "Besucher und Seitenaufrufe",
  trafficWindow: "Produktionsdaten im gewählten Zeitraum (UTC). Gesamtwerte seit Aktivierung von Vercel Web Analytics.",
  period: "Zeitraum",
  refresh: "Aktualisieren",
  today: "Heute",
  day: "Tag",
  days: "Tage",
  trend: "Verlauf",
  periodVisitors: "Besucher im Zeitraum",
  periodPageviews: "Seitenaufrufe im Zeitraum",
  viewsPerVisitor: "Aufrufe pro Besucher",
  routes: "Routen",
  share: "Anteil der Aufrufe",
  visitorsNote: "Vercel erkennt Besucher mit einem täglich erneuerten Hash. Besucher sind keine dauerhaft eindeutigen Personen und keine Sitzungen. Aufrufe pro Besucher sind keine Seiten pro Sitzung.",
  engagement: "Aufenthaltszeit",
  averageTime: "Ø sichtbare Zeit pro Seitenaufruf",
  visibleTime: "Sichtbare Zeit insgesamt",
  measuredViews: "Gemessene Seitenaufrufe",
  allTime: "Seit Messbeginn",
  engagementPeriod: "Zeitraum der Aufenthaltszeit",
  engagementWindow: "Eigener Zeitraum für diese Messung (UTC). Seit Messbeginn umfasst alle gespeicherten Zeitdaten.",
  reviews: "Website-Reviews · Serveranalyse",
  reviewsNote: "Nur gespeicherte Serveraufträge aus der Website-Review-Funktion, die über Modal verarbeitet werden. Lokale App-Analysen, Browser-Bot-Züge und Puzzle-Erstellung zählen nicht. Ein Auftrag wird pro Partie und Version einmal gezählt; erneutes Öffnen und Worker-Versuche sind keine weiteren Aufträge. Dies ist kein Modal-Abrechnungsbericht.",
  reportPeriod: "Zeitraum wie oben bei Besucher und Seitenaufrufe (UTC)",
  reviewRequests: "Angefordert im Zeitraum",
  reviewStarted: "Ausführung gestartet im Zeitraum",
  reviewCompleted: "Abgeschlossen im Zeitraum",
  reviewFailed: "Fehlgeschlagene Aufträge aus dem Zeitraum",
  reviewRequesters: "Anfordernde Konten im Zeitraum",
  reviewTotal: "Serveraufträge insgesamt",
  reviewTotalStarted: "Ausgeführte Serveraufträge insgesamt",
  reviewQueued: "Aktuell in Warteschlange",
  reviewRunning: "Aktuell in Ausführung",
  reviewTrend: "Review-Verlauf",
  recentReviews: "Letzte 20 angeforderten Server-Reviews im Zeitraum",
  reviewJob: "Auftrag",
  reviewRequestedAt: "Angefordert",
  reviewStartedAt: "Gestartet",
  reviewCompletedAt: "Abgeschlossen",
  reviewAttempts: "Worker-Versuche",
  reviewStatusQueued: "Warteschlange",
  reviewStatusRunning: "In Ausführung",
  reviewStatusCompleted: "Abgeschlossen",
  reviewStatusFailed: "Fehlgeschlagen",
  reviewHistoryNote: "Zeitpunkte und Status stammen aus dem aktuellen Auftragsdatensatz. Manuell erneut angeforderte fehlgeschlagene Aufträge werden wiederverwendet; frühere Versuche und Startzeitpunkte sind keine vollständige Ereignishistorie.",
  survey: "Preisumfrage nach der Wochenanalyse",
  surveyNote: "Freiwillige Frage nach Verbrauch der kostenlosen Wochenanalyse: Wie viel würdest du monatlich für unbegrenzte Analysen bezahlen? Je Konto zählt eine aktuelle Antwort. Eine Änderung ersetzt die vorherige Auswahl; es werden weder zusätzliche Personen noch Zahlungen gezählt.",
  surveyVoters: "Teilnehmer insgesamt",
  surveyParticipation: "Anteil aller registrierten Konten",
  surveyParticipationNote: "Bezug auf alle Konten, nicht nur auf Personen, denen die Frage angezeigt wurde.",
  surveyNewVoters: "Neue Teilnehmer im Zeitraum",
  surveyUpdatedVotes: "Aktuelle Antworten aus dem Zeitraum",
  surveyAverage: "Ø gewählter Monatspreis",
  surveyDistribution: "Aktuelle Preisverteilung · alle Antworten",
  surveyMonthlyPrice: "Monatlicher Preis",
  surveyVotes: "Teilnehmer",
  surveyShare: "Anteil der Antworten",
  surveyRecent: "Letzte 20 Antworten im Zeitraum",
  surveyCreatedAt: "Erstmals abgestimmt",
  surveyUpdatedAt: "Zuletzt gespeichert",
  engagementNote: "Eigene Messung ab diesem Deployment, ohne Cookies oder Besucherkennungen. Gezählt wird die Zeit in sichtbaren Tabs, auch während einer Partie. Meldung alle 30 Sekunden sowie beim Verlassen oder Ausblenden. Keine vollständige Sitzungsdauer; blockierte, verlorene oder noch ausstehende Meldungen können die Werte beeinflussen. Die Aufrufzahlen können von Vercel abweichen.",
  trafficUnavailable: "Vercel-Daten konnten nicht geladen werden. Web Analytics muss im Projekt aktiviert sein und WEB_ANALYTICS_VERCEL_TOKEN, WEB_ANALYTICS_PROJECT_ID sowie WEB_ANALYTICS_TEAM_ID müssen auf dem Server eingerichtet sein. Auch Tariflimits oder ein abgelaufener Token können den Abruf verhindern.",
  vercelLimitations: "Weitere Vercel-Auswertungen: UTM-Kampagnen benötigen Web Analytics Plus, eigene Events Pro oder Enterprise. Suchparameter werden hier aus Datenschutzgründen entfernt. Sitzungsdauer und Absprungrate liefert die öffentliche Web-Analytics-API nicht.",
  business: "Konten und Spielbetrieb",
  businessWindow: "Live aus der GoStone-Datenbank; Zeitfenster werden jeweils bis heute berechnet.",
  totalVisitors: "Besucher gesamt",
  totalPageviews: "Seitenaufrufe gesamt",
  accountsTotal: "Konten gesamt",
  accountsToday: "Neue Konten heute",
  accounts7d: "Neue Konten · 7 Tage",
  accounts30d: "Neue Konten · 30 Tage",
  gamesTotal: "Partien gesamt",
  gamesToday: "Neue Partien heute",
  games7d: "Neue Partien · 7 Tage",
  games30d: "Neue Partien · 30 Tage",
  activeGames: "Aktive Partien",
  finishedGames: "Beendete Partien",
  movesTotal: "Gespielte Züge gesamt",
  trafficTrend: "Verlauf · 30 Tage",
  businessTrend: "Registrierungen und Partien · 30 Tage",
  countries: "Länder",
  pages: "Seiten",
  referrers: "Herkunft",
  devices: "Geräte",
  browsers: "Browser",
  operatingSystems: "Betriebssysteme",
  recentAccounts: "Neueste Konten",
  recentGames: "Neueste Partien",
  breakdown30d: "Partie-Aufteilung · 30 Tage",
  boardSizes: "Brettgrößen",
  timeControls: "Zeitmodi",
  gameTypes: "Partiearten",
  rules: "Regeln",
  visitors: "Besucher",
  pageviews: "Aufrufe",
  date: "Datum",
  registrations: "Konten",
  games: "Partien",
  finished: "Beendet",
  account: "Konto",
  created: "Erstellt",
  lastGame: "Letzte Partie",
  players: "Spieler",
  details: "Details",
  moves: "Züge",
  status: "Status",
  noData: "Noch keine Daten in diesem Zeitraum.",
  unavailable: "Dieser Datenbereich ist vorübergehend nicht verfügbar.",
  never: "Noch keine",
  active: "Aktiv",
  complete: "Beendet",
  black: "Schwarz",
  white: "Weiß",
  versus: "gegen",
} as const;
