export const analyticsAdminCopy = {
  title: "Web Analytics",
  trafficErrorLog: "Web Analytics traffic report failed",
  businessErrorLog: "Web Analytics business report failed",
  kicker: "Interner GoStone-Bericht",
  intro: "Verkehr, Registrierungen und Spielaktivität in einer geschützten Übersicht.",
  generated: "Stand",
  protected: "Nicht verlinkt · HTTP-geschützt · nicht indexierbar",
  privacyTitle: "Datenschutzgrenze",
  privacyText: "Vercel stellt Orts- und Gerätedaten ausschließlich anonym und aggregiert bereit. Deshalb kann diese Übersicht Länder, Seiten und Geräte sowie getrennt davon GoStone-Konten und Partien zeigen, aber kein Land einer bestimmten Person oder einem bestimmten Konto zuordnen.",
  traffic: "Besucher und Seitenaufrufe",
  trafficWindow: "Aufschlüsselungen der letzten 30 Tage; Gesamtwerte seit Aktivierung von Vercel Web Analytics.",
  business: "Konten und Spielbetrieb",
  businessWindow: "Live aus der GoStone-Datenbank; Zeitfenster werden jeweils bis heute berechnet.",
  totalVisitors: "Besucher gesamt",
  totalPageviews: "Seitenaufrufe gesamt",
  accountsTotal: "Konten gesamt",
  accountsToday: "Neue Konten heute",
  accounts7d: "Neue Konten · 7 Tage",
  accounts30d: "Neue Konten · 30 Tage",
  gamesTotal: "Partien gesamt",
  gamesToday: "Neue Partien heute",
  games7d: "Neue Partien · 7 Tage",
  games30d: "Neue Partien · 30 Tage",
  activeGames: "Aktive Partien",
  finishedGames: "Beendete Partien",
  movesTotal: "Gespielte Züge gesamt",
  trafficTrend: "Verlauf · 30 Tage",
  businessTrend: "Registrierungen und Partien · 30 Tage",
  countries: "Länder",
  pages: "Seiten",
  referrers: "Herkunft",
  devices: "Geräte",
  browsers: "Browser",
  operatingSystems: "Betriebssysteme",
  recentAccounts: "Neueste Konten",
  recentGames: "Neueste Partien",
  breakdown30d: "Partie-Aufteilung · 30 Tage",
  boardSizes: "Brettgrößen",
  timeControls: "Zeitmodi",
  gameTypes: "Partiearten",
  rules: "Regeln",
  visitors: "Besucher",
  pageviews: "Aufrufe",
  date: "Datum",
  registrations: "Konten",
  games: "Partien",
  finished: "Beendet",
  account: "Konto",
  created: "Erstellt",
  lastGame: "Letzte Partie",
  players: "Spieler",
  details: "Details",
  moves: "Züge",
  status: "Status",
  noData: "Noch keine Daten in diesem Zeitraum.",
  unavailable: "Dieser Datenbereich ist vorübergehend nicht verfügbar.",
  never: "Noch keine",
  active: "Aktiv",
  complete: "Beendet",
  black: "Schwarz",
  white: "Weiß",
  versus: "gegen",
} as const;
