import type { LearnLesson, LessonStep } from "./curriculum";
import { b, w, p, t, task, mark, info, sequence, STRAIGHT_THREE, BENT_THREE, T_FOUR, SNAPBACK, NET, RACE, DOUBLE_ATARI } from "./laterLessonTools";
import { attack, bigEndgame, connect, cut, rescue, SAFE_GROUP, settledTeachingBoard, tenuki } from "./strategicPositions";

const falseEye = [b(2,1),b(1,2),b(3,2),b(2,3),w(2,0),w(1,1),w(3,1)];
const live = task("divide-eye-space",7,STRAIGHT_THREE,"black",[p(3,3)],t("Schwarz ist außen vollständig umgeben. Teile die drei Innenpunkte in zwei getrennte Augen.","Black is completely surrounded outside. Divide its three interior points into two separate eyes."),t("Die beiden übrigen Punkte sind getrennt. Weiß kann keinen davon als ersten Zug legal besetzen.","The two remaining points are separate. White cannot legally occupy either as its first move."),t("Ein Zug am Ende lässt zwei benachbarte Innenpunkte übrig, nicht zwei getrennte Augen.","Playing at an end leaves two adjacent interior points, not two separate eyes."));
const bent = task("bent-vital",7,BENT_THREE,"white",[p(2,2)],t("Die drei schwarzen Innenfreiheiten bilden ein L. Besetze den Punkt, der die beiden Arme berührt.","Black's three interior liberties form an L. Occupy the point touching both arms."),t("Schwarz kann keinen Zug zwischen die beiden verbliebenen Punkte setzen. Ohne Ausgang kann diese Gruppe keine zwei Augen bilden.","Black cannot play between the two remaining points. Without an exit this group cannot form two eyes."),t("Ein äußerer Arm lässt Schwarz den mittleren Punkt zum Teilen des Augenraums.","An outer arm leaves Black the central point for dividing the eye space."));
const nakade = task("t-vital",7,T_FOUR,"white",[p(3,2)],t("Vier Innenfreiheiten bilden ein T. Weiß spielt auf den Punkt, der alle drei Arme berührt.","Four interior liberties form a T. White plays at the point touching all three arms."),t("Der mittlere Stein verhindert getrennte Augen. Ein Stein in einem Arm ließe Schwarz die Mitte; dieser Angriff auf den Augenraum heißt Nakade.","The central stone prevents separate eyes. A stone in an arm would leave Black the center; this attack on eye space is nakade."),t("Der Arm sperrt die Mitte nicht. Suche den Schnittpunkt mit drei freien Nachbarn innerhalb der schwarzen Wand.","An arm does not block the center. Find the intersection with three empty neighbors inside Black's wall."));
const killBent = sequence("bent-proof",7,BENT_THREE,"white",[
  {move:p(2,2),replies:[p(3,2)],body:bent.body,success:t("Schwarz besetzt einen Arm. Der andere bleibt seine letzte Freiheit.","Black occupies one arm. The other remains its last liberty.")},
  {move:p(2,3),body:t("Nimm die letzte Freiheit unten im L.","Take the final liberty at the bottom of the L."),success:t("Die ganze schwarze Wand wird geschlagen. Ein Auge allein reichte hier nicht.","The whole black wall is captured. One eye alone was not enough here.")},
]);
const killT = sequence("nakade-proof",7,T_FOUR,"white",[
  {move:p(3,2),replies:[p(2,2)],body:nakade.body,success:t("Schwarz füllt links. Die Mitte bleibt von Weiß besetzt.","Black fills on the left. White still occupies the center.")},
  {move:p(4,2),replies:[p(3,3)],body:t("Besetze den rechten Arm. Schwarz wird die beiden weißen Innensteine durch Füllen unten schlagen.","Occupy the right arm. Black will capture both white interior stones by filling below."),success:t("Schwarz hat Weiß geschlagen, aber die zwei frei gewordenen Punkte sind benachbart: kein Paar getrennte Augen.","Black captured White, but the two newly empty points are adjacent: not a pair of separate eyes.")},
  {move:p(3,2),replies:[p(4,2)],body:t("Wirf erneut in der Mitte ein. Schwarz kann diesen einen Stein schlagen, bekommt dabei aber nur einen einzigen Innenpunkt frei.","Throw in at the center again. Black can capture this one stone, but gets only one interior point back."),success:t("Die schwarze Gruppe hat jetzt nur noch ein Auge als letzte Freiheit.","The black group now has just one eye as its last liberty.")},
  {move:p(3,2),body:t("Besetze die letzte Freiheit und schlage die schwarze Gruppe.","Occupy the last liberty and capture the black group."),success:t("Auch das Schlagen der Einwürfe rettete Schwarz nicht. Nakade zerstört den Raum für getrennte Augen.","Even capturing the throw-ins did not save Black. Nakade destroys space for separate eyes.")},
]);
const koBefore = [b(1,2),b(2,1),b(3,2),w(2,2),w(1,3),w(3,3),w(2,4),b(6,6),w(5,6),w(6,5)];
const koAfter = [...koBefore.filter(({x,y})=>x!==2||y!==2),b(2,3)];
const koLine = sequence("ko-threat",9,koAfter,"white",[
  {move:p(7,6),replies:[p(6,7)],body:t("Weiß darf links nicht sofort zurückschlagen. Setze rechts den schwarzen Stein in Atari.","White cannot immediately recapture on the left. Put the black stone on the right in atari."),success:t("Schwarz beantwortet das Atari rechts. Eine solche Drohung anderswo heißt Ko-Drohung.","Black answers the atari on the right. Such a threat elsewhere is a ko threat.")},
  {move:p(2,2),body:t("Beide Farben haben inzwischen anderswo gespielt. Schlage jetzt im Ko zurück.","Both colors have now played elsewhere. Recapture in the ko now."),success:t("Die unmittelbare Wiederholung ist unterbrochen. Jetzt darf Schwarz seinerseits nicht sofort zurückschlagen.","The immediate repetition is broken. Black now cannot immediately recapture in turn.")},
]);
const forcing = sequence("forcing",7,[w(2,2),b(1,2),b(2,1)],"black",[{move:p(3,2),replies:[p(2,3)],body:t("Weiß hat zwei Freiheiten. Spiele rechts Atari, damit Weiß den Stein nur durch Erweitern behalten kann.","White has two liberties. Play atari on the right so White can keep the stone only by extending."),success:t("Weiß hat geantwortet. Die Antwort ist nicht Pflicht: Weiß könnte den Stein opfern. Prüfe, ob deine Drohung wichtig genug ist.","White replied. The reply is not compulsory: White could sacrifice the stone. Check whether your threat matters enough.")}]);
const snap = sequence("read-snapback",5,SNAPBACK,"black",[
  {move:p(1,0),replies:[p(0,0)],body:t("Lies vor dem Setzen: Schwarz wirft oben ein, Weiß schlägt links. Wo kann Schwarz danach zurückschlagen? Spiele zuerst den Einwurf.","Read before playing: Black throws in above, White captures on the left. Where can Black recapture afterward? Play the throw-in first."),success:t("Weiß hat einen Stein geschlagen. Prüfe die Freiheiten der jetzt verbundenen weißen Gruppe.","White captured one stone. Check the liberties of the now connected white group.")},
  {move:p(1,0),body:t("Die weiße Dreiergruppe hat nur einen freien Nachbarn. Spiele den angekündigten Rückschlag.","The white three-stone group has only one empty neighbor. Play the recapture you predicted."),success:t("Ein schwarzer Stein wurde geopfert, drei weiße wurden geschlagen. Gelesen hast du eigenen Zug, Antwort und Fortsetzung.","One black stone was sacrificed and three white stones captured. You read your move, the reply, and the continuation.")},
]);
const countPosition = settledTeachingBoard(9);
const candidate = {...mark("candidates",9,[...SAFE_GROUP,w(5,2),w(5,5)],[p(2,6),p(3,5),p(2,7)],t("Die schwarze Gruppe links lebt. Markiere zwei verschiedene plausible Züge in der freien Ecke unten links, bevor du einen davon liest.","The black group on the left is alive. Mark two different plausible moves in the empty lower-left corner before reading one."),t("Mehrere Züge sind spielbar. Vergleiche jetzt Antwort, eigene Sicherheit und Gewinn; ein einzelner Kandidat kann eine bessere Idee verdecken.","Several moves are playable. Compare the reply, your own safety, and the gain; a single candidate can hide a better idea.")),selectionCount:2};
const final: LessonStep[] = [
  {...task("double",5,DOUBLE_ATARI,"black",[p(2,2)],t("Zwei weiße Gruppen haben je zwei Freiheiten. Bedrohe beide zugleich.","Two white groups each have two liberties. Threaten both at once."),t("Beide Gruppen stehen in Atari; Weiß kann nicht beide mit einem normalen Erweiterungszug retten.","Both groups are in atari; White cannot save both with one normal extension."),t("Suche die gemeinsame Freiheit beider weißen Gruppen.","Find the liberty shared by both white groups."))},
  live, cut(9), rescue(9), bigEndgame(9),
  {id:"full-game",kind:"beginner-game",gameSize:9,body:t("Spiele eine vollständige 9×9-Partie. Markiere am Ende tote Gruppen und neutrale Punkte, bestätige die Wertung und betrachte danach die konkreten Lernmomente.","Play a complete 9×9 game. At the end mark dead groups and neutral points, confirm scoring, then inspect the concrete learning moments.")},
];
export const STAGE_EIGHT: readonly LearnLesson[] = [
  {id:"s8-life-death",stage:8,title:t("Augenraum lesen","Reading eye space"),minutes:4,steps:[live,...killBent]},
  {id:"s8-nakade",stage:8,title:t("Nakade: den Augenraum besetzen","Nakade: occupying eye space"),minutes:4,steps:[...killT,{...nakade,id:"defend-t",toPlay:"black",success:t("Schwarz besetzt den Knotenpunkt zuerst. Die drei übrigen Innenpunkte sind getrennte Augen.","Black occupies the junction first. The three remaining interior points are separate eyes."),body:t("Dieselbe Form, aber Schwarz beginnt. Besetze den Knotenpunkt, bevor Weiß den Augenraum zerstört.","The same shape, but Black moves first. Occupy the junction before White destroys the eye space.")}]},
  {id:"s8-eye-shapes",stage:8,title:t("Sichere und falsche Augen","Secure and false eyes"),minutes:4,steps:[mark("real-eyes",9,SAFE_GROUP,[p(1,2),p(3,2)],t("Markiere die zwei getrennten Augen der verbundenen schwarzen Gruppe.","Mark the connected black group's two separate eyes."),t("Jedes Auge ist von derselben Gruppe umgeben. Ein weißer Zug in nur eines davon wäre Selbstmord.","Each eye is surrounded by the same group. A white move in just one would be suicide.")),task("false-eye",5,falseEye,"white",[p(2,2)],t("Der obere schwarze Randstein hat nur noch die scheinbare Augenfreiheit. Besetze sie als Weiß.","The upper black boundary stone has only the apparent eye liberty left. Occupy it as White."),t("Weiß schlägt den oberen Randstein. Der Punkt war kein sicheres Auge: Seine Randsteine waren nicht sicher verbunden.","White captures the upper boundary stone. The point was not a secure eye: its boundary stones were not securely connected."),t("Prüfe den oberen Randstein: Sein letzter freier Nachbar liegt innen.","Check the upper boundary stone: its last empty neighbor lies inside."))]},
  {id:"s8-semeai",stage:8,title:t("Gemeinsame und äußere Freiheiten","Shared and outside liberties"),minutes:4,steps:[mark("shared",5,[b(1,1),w(2,2)],[p(2,1),p(1,2)],t("Markiere die Freiheiten, die beide Gruppen gleichzeitig berühren.","Mark the liberties touching both groups at once."),t("Diese zwei Freiheiten sind gemeinsam. Sie dürfen beim Vergleich nicht wie unabhängige äußere Freiheiten behandelt werden.","These two liberties are shared. Do not treat them as independent outside liberties when comparing groups.")),mark("outer",5,[b(1,1),w(2,2)],[p(0,1),p(1,0)],t("Markiere nur die äußeren Freiheiten von Schwarz: Weiß berührt sie nicht.","Mark only Black's outside liberties: White does not touch them."),t("Diese zwei Punkte gehören nur zur schwarzen Freiheitenseite. Prüfe außerdem Augen, Schlagmöglichkeiten und wer beginnt.","These two points are liberties only for Black. Also check eyes, captures, and who moves first.")),...sequence("race",5,RACE,"black",[{move:p(2,0),replies:[p(0,2)],body:t("Schwarz hat vier, Weiß drei äußere Freiheiten. Beginne mit der weißen Freiheit oben.","Black has four outside liberties, White three. Begin with White's upper liberty."),success:t("Beide Gruppen verlieren eine Freiheit.","Both groups lose one liberty.")},{move:p(2,2),replies:[p(1,2)],body:t("Nimm die weiße Freiheit unten links.","Take White's lower-left liberty."),success:t("Weiß steht im Atari. Schwarz hat noch zwei Freiheiten und ist am Zug.","White is in atari. Black has two liberties left and moves next.")},{move:p(3,2),body:t("Schlage, bevor Weiß deine letzten Freiheiten nehmen kann.","Capture before White can take your remaining liberties."),success:t("Die geschlagenen Steine geben Schwarz neue Freiheiten. Ein bloßer Zahlenvergleich ohne Zugreihenfolge reicht nicht.","The captured stones give Black new liberties. Comparing counts without move order is not enough.")}])]},
  {id:"s8-ko-threats",stage:8,title:t("Ko-Drohungen","Ko threats"),minutes:4,steps:[{id:"blocked",kind:"illegal",size:9,stones:koAfter,toPlay:"white",targets:[p(2,2)],koPreviousBoard:koBefore,expectedError:"ko",body:t("Schwarz hat links gerade geschlagen. Versuche als Weiß sofort zurückzuschlagen.","Black just captured on the left. Try to recapture immediately as White."),success:t("Ko verhindert die sofortige Wiederholung. Weiß braucht zuerst einen Zug anderswo.","Ko prevents immediate repetition. White first needs a move elsewhere.")},...koLine]},
  {id:"s8-ko-strategy",stage:8,title:t("Ein Ko ist nicht um jeden Preis wichtig","A ko is not worth every cost"),minutes:4,steps:[...koLine,task("save-larger",9,[...koAfter,b(7,3),b(7,4),w(6,3),w(7,2),w(8,3),w(6,4),w(8,4)],"black",[p(7,5)],t("Links steht ein einzelner Stein im Ko. Rechts hat eine schwarze Zweiergruppe nur eine Freiheit. Rette zuerst die Zweiergruppe statt für den einen Stein weiterzukämpfen.","There is one ko stone on the left. On the right a black pair has one liberty. Save the pair first instead of fighting on for the one stone."),t("Schwarz gibt das kleine Ko notfalls auf. Vergleiche den Verlust im Ko mit dem Verlust beim Ignorieren einer Drohung.","Black is willing to give up the small ko. Compare losing the ko with losing by ignoring a threat."),t("Der Ko-Stein ist nicht die einzige Gruppe. Prüfe die letzte Freiheit der rechten Zweiergruppe.","The ko stone is not the only group. Check the right pair's last liberty."))]},
  {id:"s8-fighting-shape",stage:8,title:t("Form im Kontaktkampf","Shape in contact fights"),minutes:3,steps:[connect(9),cut(9),rescue(9)]},
  {id:"s8-haengma",stage:8,title:t("Wie Steine gemeinsam weiterlaufen","How stones develop together"),minutes:3,steps:[task("jump",9,[b(3,3),w(5,3)],"black",[p(3,5)],t("Weiß steht rechts. Springe mit einem freien Punkt Abstand nach unten, weg vom weißen Stein.","White stands on the right. Jump downward with one empty point between stones, away from White."),t("Der Ein-Punkt-Sprung entwickelt Raum schneller als ein direkter Anschluss. Er ist nicht physisch verbunden; ein Schnitt muss weiterhin gelesen werden.","The one-point jump develops space faster than a direct extension. It is not physically connected; a cut still needs reading."),t("Gesucht ist ein Sprung mit genau einem freien Schnittpunkt dazwischen.","Look for a jump with exactly one empty intersection between.")),connect(9)]},
  {id:"s8-cutting-points",stage:8,title:t("Schnittpunkte erkennen","Recognizing cutting points"),minutes:3,steps:[cut(9),connect(9)]},
  {id:"s8-forcing",stage:8,title:t("Drohung und Antwort","Threat and reply"),minutes:3,steps:[...forcing,tenuki(9)]},
  {id:"s8-sabaki",stage:8,title:t("Mit wenig Steinen Raum finden","Finding space with few stones"),minutes:3,steps:[task("light",9,[b(3,3),w(3,2),w(4,3),w(4,4)],"black",[p(2,5),p(3,5)],t("Der schwarze Stein ist rechts eingeengt. Setze mit Abstand nach unten in freien Raum statt dich eng gegen die weiße Wand zu drücken.","The black stone is cramped on the right. Play with space downward into open room instead of pressing tightly against White's wall."),t("Der neue Stein hat freien Raum. Leichtes Entwickeln heißt Sabaki: Nicht jeden Stein fest anbinden, aber mögliche Schnitte und Opfer vorher lesen.","The new stone has open space. Light development is sabaki: do not attach every stone tightly, but read possible cuts and sacrifices first."),t("Direkt rechts steht die weiße Wand. Freier Raum liegt unter den Steinen.","White's wall is immediately to the right. Open space is below the stones.")),rescue(9)]},
  {id:"s8-attack-defense",stage:8,title:t("Angreifen oder zuerst verteidigen?","Attack or defend first?"),minutes:4,steps:[rescue(9),attack(9),tenuki(9)]},
  {id:"s8-thickness",stage:8,title:t("Von sicheren Gruppen aus spielen","Playing from secure groups"),minutes:3,steps:[tenuki(13),attack(13)]},
  {id:"s8-overconcentration",stage:8,title:t("Nicht schon sicheren Raum doppelt besetzen","Do not occupy already secure space twice"),minutes:3,steps:[tenuki(9),task("spread",9,[b(3,3),b(3,4),b(4,3),b(4,4),w(6,2)],"black",[p(2,6),p(3,6)],t("Vier schwarze Steine stehen dicht im Quadrat. Erweitere nach unten statt noch einen Stein an den Block zu kleben.","Four black stones sit tightly in a square. Extend downward instead of attaching another stone to the block."),t("Schwarz beansprucht neuen Raum. Viele Steine im selben kleinen Bereich heißen Überkonzentration, wenn sie keine zusätzliche Aufgabe erfüllen.","Black claims new space. Many stones in the same small region are overconcentrated when they serve no additional purpose."),t("Ein fünfter Stein direkt am Block ändert hier wenig. Unten liegt freier Raum.","A fifth stone immediately beside the block changes little here. There is open space below."))]},
  {id:"s8-endgame-values",stage:8,title:t("Endspielpunkte vergleichen","Comparing endgame points"),minutes:3,steps:[bigEndgame(9),info("gain-not-swing",9,[b(0,2),b(1,2),b(2,2),b(2,1),b(2,0),w(5,3)],t("Oben wurden vier eigene Gebietspunkte eingeschlossen. Ein Endspielwert vergleicht beide möglichen Ergebnisse, nicht nur den Gewinn eines Spielers. Ob der Gegner antworten muss, verändert die Reihenfolge.","Four own territory points were enclosed above. An endgame value compares both possible outcomes, not only one player's gain. Whether the opponent must reply changes the order."))]},
  {id:"s8-sente-endgame",stage:8,title:t("Antworten im Endspiel","Replies in the endgame"),minutes:3,steps:[...forcing,bigEndgame(9)]},
  {id:"s8-counting",stage:8,title:t("Sicheres Gebiet und unsicherer Raum","Secure territory and unsettled space"),minutes:3,steps:[mark("count",9,countPosition,[p(0,0),p(2,0),p(0,3),p(2,3)],t("Markiere vier leere schwarze Gebietspunkte oben links. Steine zählen in der japanischen Wertung nicht als Gebietspunkte.","Mark four empty Black territory points at the upper left. Stones are not territory points under Japanese scoring."),t("Vier Punkte wurden markiert. Zähle die übrigen geschlossenen Regionen getrennt; der offene Mittelstreifen berührt beide Farben und ist neutral.","Four points were marked. Count the other enclosed regions separately; the open middle strip touches both colors and is neutral.")),info("prisoners-komi",9,countPosition,t("Zur vollständigen Wertung gehören Gebiet, Gefangene, vereinbarte tote Steine und Weißs 6,5 Komi. In einer laufenden Partie bleiben offene Gebiete nur Schätzungen.","A full score includes territory, prisoners, agreed dead stones, and White's 6.5 komi. During a game open areas remain estimates."))]},
  {id:"s8-reading",stage:8,title:t("Zug, Antwort, Fortsetzung","Move, reply, continuation"),minutes:4,steps:[...snap,...sequence("read-net",5,NET,"black",[{move:p(2,2),replies:[p(2,1)],body:t("Weiß kann rechts oder unten laufen. Lege zuerst das Netz diagonal an, dann prüfe die rechte Flucht.","White can run right or down. Set the net diagonally first, then check the right escape."),success:t("Weiß läuft rechts. Lies weiter: Welcher Randpunkt nimmt der weißen Gruppe diese Flucht?","White runs right. Read further: which edge point blocks this escape?")},{move:p(2,0),replies:[p(1,2)],body:t("Blockiere die rechte Flucht am oberen Rand.","Block the right escape at the top edge."),success:t("Weiß versucht jetzt nach unten zu laufen. Auch diese Freiheit liegt innerhalb des Netzes.","White now tries to run down. This liberty is inside the net too.")},{move:p(0,2),body:t("Schlage die Gruppe an ihrem letzten freien Nachbarn am linken Rand.","Capture the group at its last empty neighbor on the left edge."),success:t("Die gelesene Folge deckt beide Fluchten ab. Ein Netz nimmt Raum statt bei jedem Zug Atari zu geben.","The line you read covers both escapes. A net removes space instead of giving atari at every move.")}])]},
  {id:"s8-candidates",stage:8,title:t("Mehrere Kandidaten suchen","Finding several candidates"),minutes:3,steps:[candidate,tenuki(9)]},
  {id:"s8-review",stage:8,title:t("Die eigene Partie untersuchen","Reviewing your own game"),minutes:3,steps:[mark("review-group",9,[...SAFE_GROUP,b(5,5),w(4,5),w(5,4),w(6,5)],[p(5,5)],t("Du suchst einen Lernmoment nach der Partie. Markiere die eigene Gruppe, die gerade nur eine Freiheit hatte.","You are looking for a learning moment after a game. Mark the own group that just had one liberty."),t("Gehe in deiner Partie zu dieser Stellung zurück: Was drohte, welche Kandidaten hattest du und was passierte nach deinem Zug? Untersuche zwei oder drei Momente, nicht jeden Zug.","Return to this position in your game: what was threatened, what candidates did you have, and what happened after your move? Examine two or three moments, not every move."),"stone"),rescue(9),{...info("open-review",9,countPosition,t("Öffne eine eigene abgeschlossene Partie in der Analyse. Gehe zuerst ohne KI zur ersten unsicheren Gruppe zurück und spiele eine mögliche Verbesserung als Variante.","Open one of your completed games in analysis. First return to the first unsettled group without AI and play a possible improvement as a variation.")),links:["review"]}]},
  {id:"s8-ai-analysis",stage:8,title:t("KI-Vorschläge auf dem Brett prüfen","Checking AI suggestions on the board"),minutes:3,steps:[candidate,{...info("analysis-values",9,countPosition,t("Die Analyse zeigt Zugvorschläge und Bewertungen. Das sind Schätzungen der Engine, keine garantierten Ergebnisse. Spiele die vorgeschlagene Variante nach und prüfe Freiheiten, Augenraum und Gebiet.","Analysis shows suggested moves and evaluations. These are engine estimates, not guaranteed results. Play through the suggested variation and inspect liberties, eye space, and territory.")),links:["review"]},rescue(9)]},
  {id:"s8-final",stage:8,title:t("Abschluss: lesen und selbst spielen","Finish: read and play independently"),minutes:20,challenge:true,steps:final},
];
