import type { LearnLesson } from "./curriculum";
import { b, w, p, t, task, mark, info, sequence } from "./laterLessonTools";
import { approach, attack, corners, extension, framework, invasion, reduction, rescue, SAFE_GROUP, settledTeachingBoard, tenuki, weakStones } from "./strategicPositions";

const early = task("free-corner",19,[b(3,3),w(15,15)],"black",[p(3,15),p(2,16),p(15,3),p(16,2),p(2,15),p(15,2)],t("Zwei Ecken sind noch frei. Beanspruche eine davon, bevor du dicht neben einen eigenen Stein setzt.","Two corners remain open. Claim one before playing tightly beside an own stone."),t("Der neue Eckstein verteilt deine Stärke über das ganze Brett. 9×9 bleibt daneben ein eigener vollwertiger Modus.","The new corner stone distributes your strength across the whole board. 9×9 remains a full game mode alongside it."),t("Suche die freie Ecke oben rechts oder unten links.","Look for the open upper-right or lower-left corner."));
const context = task("toward-space",19,[b(3,2),b(3,7),w(15,3)],"black",[p(6,2),p(7,2)],t("Der schwarze Eckstein ist zum oberen Rand niedriger. Links unten steht schon Unterstützung; erweitere diesmal entlang der offenen oberen Seite.","The black corner stone is lower toward the top edge. Support already stands below on the left; extend along the open top side this time."),t("Du beanspruchst zusätzlichen freien Raum statt bereits besetzten Raum noch einmal zu sichern.","You claim additional open space instead of defending already occupied space again."),t("Links unten stehen bereits schwarze Steine. Die größere freie Seite liegt oben rechts von der Ecke.","Black stones already stand below on the left. The larger open side lies above and right of the corner."));
const settled = settledTeachingBoard(19);
const lastBoundary = settled.filter(({x,y})=>!(y===3&&(x===7||x===8)));
export const STAGE_SEVEN: readonly LearnLesson[] = [
  {id:"s7-bigger",stage:7,title:t("Das 19×19-Brett","The 19×19 board"),minutes:3,steps:[info("scale",19,[],t("Auf 19×19 bleiben lokale Gebiete länger offen. Die Wirkung eines Zuges auf andere Gruppen und freie Ecken wird wichtiger.","On 19×19, local territories stay open longer. A move's effect on other groups and open corners matters more.")),early]},
  {id:"s7-fuseki",stage:7,title:t("Stärke verteilen / Fuseki","Distributing strength / fuseki"),minutes:3,steps:[task("opening",19,[],"black",corners(19),t("Setze einen frühen Stein in eine Ecke, auf einen 3-3-, 3-4- oder 4-4-Punkt.","Place an early corner stone on a 3-3, 3-4, or 4-4 point."),t("Die ersten Züge verteilen Stärke über das Brett. Diese Eröffnungsphase heißt Fuseki; der gewählte Punkt ist nicht die einzig mögliche Eröffnung.","The first moves distribute strength over the board. This opening phase is fuseki; the chosen point is not the only possible opening."),t("Die äußerste Randlinie bietet wenig Wirkung nach außen. Wähle einen der frühen Eckpunkte weiter innen.","The very edge offers little outward reach. Choose an early corner point further inside.")),early]},
  {id:"s7-corners",stage:7,title:t("Freie Ecken zuerst","Open corners first"),minutes:3,steps:[early,{...early,id:"third-corner",stones:[b(3,3),w(15,15),b(3,15)],targets:[p(15,3),p(16,2),p(15,2)],body:t("Drei Ecken sind besetzt. Spiele in die letzte freie Ecke, nicht neben deine sichere linke Ecke.","Three corners are occupied. Play in the final open corner, not beside your secure left corner.")}]},
  {id:"s7-star-point",stage:7,title:t("Der 4-4-Punkt","The 4-4 point"),minutes:3,steps:[task("star",19,[],"black",[p(3,3)],t("Setze auf die vierte Linie vom oberen und linken Rand.","Play on the fourth line from the top and left edges."),t("Dieser 4-4-Punkt heißt Sternpunkt. Er ist flexibel nach beiden Seiten, verhindert aber keine 3-3-Invasion.","This 4-4 point is a star point. It is flexible toward both sides, but does not prevent a 3-3 invasion."),t("Zähle von beiden Rändern vier Linien.","Count four lines from both edges.")),...invasion(19)]},
  {id:"s7-komoku",stage:7,title:t("3-4 / Komoku","3-4 / komoku"),minutes:3,steps:[task("komoku",19,[],"black",[p(3,2),p(2,3)],t("Setze oben links einen 3-4-Punkt.","Place an upper-left 3-4 stone."),t("3-4 heißt Komoku. Der unterschiedliche Randabstand gibt der Ecke eine Richtung; weder diese noch die gedrehte Variante ist pauschal besser.","3-4 is komoku. Different edge distances give the corner a direction; neither this nor the rotated version is universally better."),t("Drei Linien von einem Rand, vier vom anderen.","Three lines from one edge, four from the other.")),context]},
  {id:"s7-san-san",stage:7,title:t("3-3 / San-san","3-3 / san-san"),minutes:3,steps:[task("san-san",19,[],"black",[p(2,2)],t("Setze auf die dritte Linie von beiden Rändern.","Play on the third line from both edges."),t("3-3 heißt San-san und liegt niedrig in der Ecke. Es nimmt eher direktes Eckgebiet in den Blick als weiten Außeneinfluss.","3-3 is san-san and sits low in the corner. It focuses more on direct corner territory than broad outside influence."),t("Die Randlinie ist die erste Linie.","The edge line is the first line.")),extension(19)]},
  {id:"s7-approach",stage:7,title:t("Annäherungszüge","Approach moves"),minutes:3,steps:[approach(19),{...approach(19),id:"approach-other",targets:[p(5,2)],body:t("Nähere dich in der zurückgesetzten Stellung von der oberen Seite.","In the reset position, approach from the top side.")}]},
  {id:"s7-extension",stage:7,title:t("Ecke und Seite verbinden","Developing corner and side"),minutes:3,steps:[extension(19),context]},
  {id:"s7-joseki",stage:7,title:t("Was ist Joseki?","What is a joseki?"),minutes:3,steps:[...invasion(19),info("local-result",19,[b(2,2),b(2,3),b(2,4),w(3,2),w(3,3),w(3,4),w(3,5)],t("Joseki sind bekannte lokale Sequenzen mit normalerweise vernünftigen Ergebnissen für beide Seiten. Dies ist der Anfang einer Ecksequenz: Schwarz innen, Weiß außen. Ob sie zum Brett passt, ist eine andere Frage.","Joseki are known local sequences with normally reasonable outcomes for both sides. This is the start of a corner sequence: Black inside, White outside. Whether it fits the board is a separate question."))]},
  {id:"s7-context",stage:7,title:t("Die Umgebung verändert den Zug","The surroundings change the move"),minutes:3,steps:[context,task("other-environment",19,[b(3,2),b(7,2),w(15,3)],"black",[p(2,5),p(2,6)],t("Derselbe Eckstein: Jetzt steht die Unterstützung schon oben. Erweitere entlang der freien linken Seite.","The same corner stone: support is now already above. Extend along the open left side."),t("Derselbe lokale Anfang braucht hier eine andere Richtung. Lerne die Funktion einer Sequenz, nicht nur ihre Reihenfolge.","The same local start needs a different direction here. Learn what a sequence does, not only its order."),t("Oben ist bereits schwarzer Raum beansprucht. Die offene Seite liegt links unten.","Black already claimed space above. The open side lies below on the left."))]},
  {id:"s7-direction",stage:7,title:t("Angriffsrichtung auf 19×19","Attack direction on 19×19"),minutes:3,steps:[context,attack(19),rescue(19)]},
  {id:"s7-thickness",stage:7,title:t("Eine sichere Außenseite","Thickness"),minutes:3,steps:[mark("safe",19,[...SAFE_GROUP,w(15,15)],SAFE_GROUP.map(({x,y})=>p(x,y)),t("Markiere die schwarze Gruppe mit zwei getrennten Augen links oben.","Mark the black group with two separate eyes at the upper left."),t("Diese Gruppe braucht keinen weiteren Rettungszug. Ihre Sicherheit und Außenseite können andere Züge unterstützen: Das nennt man Dicke oder Thickness.","This group needs no extra rescue move. Its security and outside strength can support other moves: this is thickness."),"stone"),tenuki(19)]},
  {id:"s7-weak-groups",stage:7,title:t("Welche Gruppe braucht Hilfe?","Which group needs help?"),minutes:3,steps:[mark("weak",19,weakStones(19),[p(15,15)],t("Vergleiche Augenraum und Freiheiten. Tippe die schwarze Gruppe an, die zuerst Hilfe braucht.","Compare eye space and liberties. Tap the black group that needs help first."),t("Nicht die Steinzahl entscheidet: Der einzelne Stein unten rechts hat nur eine Freiheit und keine Augen.","Stone count is not decisive: the lone lower-right stone has one liberty and no eyes."),"stone"),rescue(19)]},
  {id:"s7-profit",stage:7,title:t("Mit Gewinn angreifen","Attack for profit"),minutes:3,steps:[attack(19),tenuki(19)]},
  {id:"s7-moyo",stage:7,title:t("Große Rahmen erkennen","Recognizing large frameworks"),minutes:3,steps:[{...mark("framework",19,framework(19),[p(13,4),p(14,4),p(13,5),p(14,5),p(13,6),p(14,6)],t("Markiere drei Punkte im möglichen weißen Rahmen rechts, nicht am linken schwarzen Stein.","Mark three points in White's potential framework on the right, not near the left black stone."),t("Die losen weißen Steine umrahmen Raum, schließen ihn aber nicht ab. Die markierten Punkte sind noch keine sicheren weißen Punkte.","The loose white stones frame space, but do not close it. The marked points are not yet secure White points.")),selectionCount:3},reduction(19)]},
  {id:"s7-invasion",stage:7,title:t("Eine Invasion beginnen","Starting an invasion"),minutes:3,steps:invasion(19)},
  {id:"s7-reduction",stage:7,title:t("Ein Moyo verkleinern","Reducing a moyo"),minutes:3,steps:[reduction(19),...invasion(19)]},
  {id:"s7-tenuki",stage:7,title:t("Tenuki auf großem Brett","Tenuki on a large board"),minutes:3,steps:[tenuki(19),rescue(19)]},
  {id:"s7-middle-game",stage:7,title:t("Wenn Gruppen in Kontakt kommen","When groups meet"),minutes:3,steps:[info("phase",19,weakStones(19),t("Es gibt keine feste Zugnummer für das Mittelspiel. Wenn Gruppen in Kontakt kommen, werden Angreifen, Verbinden und Verteidigen wichtiger als eine weitere freie Ecke.","There is no fixed move number for the middle game. When groups meet, attacking, connecting, and defending matter more than another open corner.")),rescue(19),attack(19)]},
  {id:"s7-endgame",stage:7,title:t("Von Kämpfen zu Grenzen","From fights to boundaries"),minutes:3,steps:[task("last-boundary",19,lastBoundary,"black",[p(8,3)],t("Die großen Gruppen dieser Lehrstellung haben mehrere Augen. Links in der Mitte ist die Grenze noch offen. Schließe die Lücke zur neutralen Mittellinie.","The large groups in this teaching position have several eyes. On the left near the middle, the boundary is still open. Close the gap facing the neutral central line."),t("Jetzt verändert der Zug Gebietspunkte statt das Überleben einer Gruppe. Die Partie ist in der Endspielphase.","The move now changes territory points rather than a group's survival. The game is in its endgame phase."),t("Suche die Öffnung rechts neben dem fehlenden schwarzen Stein auf der vierten Linie von oben.","Look for the opening to the right of the missing black stone on the fourth line from the top."))]},
  {id:"s7-commented-opening",stage:7,title:t("Eine 19×19-Eröffnung durchspielen","Walk through a 19×19 opening"),minutes:4,steps:sequence("opening-record",19,[],"black",[
    {move:p(3,3),replies:[p(15,15)],body:t("Beginne mit Schwarz am 4-4-Punkt links oben. Weiß wählt die gegenüberliegende Ecke.","Start with Black at the upper-left 4-4 point. White chooses the opposite corner."),success:t("Zwei Ecken sind beansprucht, zwei bleiben frei.","Two corners are claimed; two remain open.")},
    {move:p(3,15),replies:[p(15,3)],body:t("Beanspruche links unten eine zweite Ecke. Weiß besetzt die letzte freie Ecke.","Claim a second corner at the lower left. White occupies the final free corner."),success:t("Die Ecksteine sind verteilt. Nun wirken die Züge stärker auf die Seiten.","The corner stones are distributed. Moves now focus more on the sides.")},
    {move:p(2,6),replies:[p(16,12)],body:t("Erweitere vom linken oberen Eckstein entlang der linken Seite, auf der dritten Linie.","Extend from the upper-left corner stone along the left side on the third line."),success:t("Die Seitenerweiterung beansprucht Raum zwischen den Ecken.","The side extension claims space between the corners.")},
    {move:p(6,16),replies:[p(12,2)],body:t("Entwickle jetzt die untere Seite vom linken unteren Eckstein nach rechts.","Now develop the bottom side to the right of the lower-left corner stone."),success:t("Diese Eröffnung verteilt Stärke, ohne schon endgültige Gebietsgrenzen festzulegen.","This opening distributes strength without setting final territory boundaries yet.")},
  ])},
  {id:"s7-first-game",stage:7,title:t("Deine erste 19×19-Partie","Your first 19×19 game"),minutes:25,challenge:true,steps:[{id:"game",kind:"beginner-game",gameSize:19,body:t("Spiele eine vollständige 19×19-Partie gegen den lokalen Beginner Bot. Du kannst das Brett vergrößern, um präzise zu setzen.","Play a full 19×19 game against the local Beginner Bot. You can enlarge the board for precise placement."),task:t("Zwei Pässe, tote Gruppen prüfen, Wertung bestätigen. Ein Sieg ist nicht erforderlich.","Two passes, check dead groups, confirm scoring. A win is not required.")}]},
];
