import type { LearnLesson } from "./curriculum";
import { b, w, p, t, task, mark, info } from "./laterLessonTools";
import { approach, attack, commentedGame, extension, framework, invasion, reduction, SAFE_GROUP, rescue, tenuki } from "./strategicPositions";

export const STAGE_SIX: readonly LearnLesson[] = [
  {id:"s6-bigger",stage:6,title:t("9×9 oder 13×13","9×9 or 13×13"),minutes:3,steps:[
    info("nine",9,[b(3,3),w(5,5)],t("9×9 bleibt ein vollwertiger Spielmodus. Hier wirken zwei frühe Steine schon auf einen großen Teil des Bretts.","9×9 remains a full game mode. Here two early stones already influence a large part of the board.")),
    task("thirteen",13,[b(3,3),w(9,9)],"black",[p(2,10),p(3,9),p(9,3),p(10,2)],t("Auf 13×13 sind noch zwei Ecken frei. Die Regeln ändern sich nicht; beanspruche eine davon.","On 13×13, two corners are still open. The rules do not change; claim one of them."),t("Ein lokaler Kampf ist auf größerem Brett nicht immer dringender als freier Raum anderswo.","On a larger board, a local fight is not always more urgent than open space elsewhere."),t("Suche eine unbesetzte Ecke statt direkt an einen vorhandenen Stein anzulegen.","Look for an open corner instead of attaching directly to an existing stone.")),
  ]},
  {id:"s6-corner-side-center",stage:6,title:t("Ecke, Seite, Zentrum","Corner, side, center"),minutes:3,steps:[
    mark("corner",13,[b(0,1),b(1,0),w(10,10)],[p(0,0)],t("Zwei schwarze Steine und zwei Brettränder begrenzen einen Eckpunkt. Markiere ihn.","Two black stones and two board edges enclose one corner point. Mark it."),t("In der Ecke helfen zwei Ränder beim Umschließen.","Two edges help surround territory in a corner.")),
    mark("side",13,[b(0,2),b(0,4),b(1,3),w(10,10)],[p(0,3)],t("An der Seite braucht Schwarz drei direkte Nachbarn für denselben einen freien Punkt. Markiere ihn.","At the side, Black needs three direct neighbors for the same one empty point. Mark it."),t("An der Seite hilft nur ein Rand.","At the side, only one edge helps.")),
    mark("center",13,[b(5,6),b(7,6),b(6,5),b(6,7),w(10,10)],[p(6,6)],t("Im Zentrum müssen vier direkte Nachbarn den Punkt begrenzen. Markiere den Innenpunkt.","In the center, four direct neighbors must enclose the point. Mark the inner point."),t("Kein Rand hilft. Deshalb ist frühes Eckgebiet oft mit weniger Steinen erreichbar.","No edge helps. That is why early corner territory often needs fewer stones.")),
  ]},
  {id:"s6-corner-points",stage:6,title:t("3-3, 4-4 und 3-4","3-3, 4-4 and 3-4"),minutes:3,steps:[
    task("three-three",13,[],"black",[p(2,2)],t("Zähle vom oberen und linken Rand: Setze auf die jeweils dritte Linie, den 3-3-Punkt.","Count from the top and left edges: play on the third line from both, the 3-3 point."),t("3-3 liegt nahe an beiden Rändern und zielt stärker auf direktes Eckgebiet.","3-3 lies near both edges and focuses more on direct corner territory."),t("Die Randlinie zählt als erste Linie.","The edge line counts as the first line.")),
    task("four-four",13,[],"black",[p(3,3)],t("Setze auf die vierte Linie von beiden Rändern: 4-4.","Play on the fourth line from both edges: 4-4."),t("4-4 wirkt weiter nach außen, sichert die Ecke aber noch nicht gegen 3-3.","4-4 works further outward, but does not yet secure the corner against 3-3."),t("Zähle vier Linien von oben und links.","Count four lines from the top and left.")),
    task("three-four",13,[],"black",[p(2,3),p(3,2)],t("Setze auf einen 3-4-Punkt oben links. Zwei gedrehte Varianten sind möglich.","Play an upper-left 3-4 point. Two rotated versions are possible."),t("3-4 liegt zu einem Rand niedriger als zum anderen. Damit bekommt der Eckstein eine Richtung zu einer Seite.","3-4 is lower toward one edge than the other. This gives the corner stone a direction toward one side."),t("Ein Abstand muss drei Linien, der andere vier Linien sein.","One distance must be three lines, the other four.")),
  ]},
  {id:"s6-approach",stage:6,title:t("Eine Ecke annähern","Approaching a corner"),minutes:3,steps:[approach(13),{...approach(13),id:"other-direction",targets:[p(2,5)],body:t("Nähere dich in derselben Stellung diesmal von der linken Seite, auf der dritten Linie.","In the same position, approach from the left side this time, on the third line.")}]},
  {id:"s6-extension",stage:6,title:t("An der Seite erweitern","Extending along the side"),minutes:3,steps:[extension(13),{...extension(13),id:"space",targets:[p(2,6)],body:t("Die Stellung ist wieder am Anfang. Probiere den weiter entfernten der beiden zuvor erlaubten Erweiterungspunkte.","The position has reset. Try the more distant of the two previously allowed extension points.")}]},
  {id:"s6-base",stage:6,title:t("Eine Basis für Augen","A base for eyes"),minutes:3,steps:[
    task("side-space",13,[b(2,3),w(4,3)],"black",[p(2,5),p(2,6)],t("Weiß steht außerhalb deiner Seitengruppe. Erweitere entlang des Randes, um darunter Raum für Augen offenzuhalten.","White stands outside your side group. Extend along the edge to keep space for eyes below it."),t("Der Raum zwischen Gruppe und Rand heißt Basis. Er bietet Chancen für Augen, garantiert aber noch kein Leben.","The space between the group and edge is a base. It offers chances for eyes, but does not guarantee life yet."),t("Spiele entlang der linken Seite, nicht weiter in den weißen Einfluss nach rechts.","Play along the left side, not further right into White's influence.")),
    mark("room",13,[b(2,3),b(2,5),w(4,3)],[p(0,4),p(1,4)],t("Markiere zwei freie Punkte zwischen Schwarz und dem linken Rand, die zum möglichen Augenraum gehören.","Mark two empty points between Black and the left edge that belong to its possible eye space."),t("Der Raum ist noch offen. Später musst du die Grenzen gegen Angriffe sichern.","The space is still open. Later you must secure its boundaries against attacks.")),
  ]},
  {id:"s6-influence",stage:6,title:t("Eine Außenseite nutzen","Using outside influence"),minutes:3,steps:[info("not-territory",13,[...SAFE_GROUP,w(5,5)],t("Die schwarze Gruppe links hat zwei Augen und braucht keinen Rettungszug. Ihre Außenseite kann nahe neue Steine unterstützen.","The black group on the left has two eyes and needs no rescue. Its outside position can support nearby new stones.")),attack(13)]},
  {id:"s6-moyo",stage:6,title:t("Ein Rahmen, noch kein Gebiet","A framework, not territory yet"),minutes:3,steps:[
    {...mark("potential",13,framework(13),[p(7,4),p(8,4),p(7,5),p(8,5),p(7,6),p(8,6)],t("Markiere drei freie Punkte innerhalb des losen weißen Rahmens rechts.","Mark three empty points inside White's loose framework on the right."),t("Dieser mögliche Gebietsrahmen heißt Moyo. Er ist nicht geschlossen; Schwarz kann ihn verkleinern oder hineinspielen.","This potential-territory framework is a moyo. It is not closed; Black can reduce it or enter it.")),selectionCount:3},reduction(13),
  ]},
  {id:"s6-reduction",stage:6,title:t("Von außen verkleinern","Reducing from outside"),minutes:3,steps:[reduction(13),{...reduction(13),id:"second-reduction",targets:[p(5,6)],body:t("Probiere in der zurückgesetzten Stellung einen Zug am unteren Teil der offenen linken Moyo-Grenze.","In the reset position, try a move on the lower part of the moyo's open left boundary.")}]},
  {id:"s6-invasion",stage:6,title:t("Hineinspielen / Invasion","Entering / invasion"),minutes:3,steps:invasion(13)},
  {id:"s6-invasion-reduction",stage:6,title:t("Innen oder am Rand?","Inside or at the edge?"),minutes:3,steps:[reduction(13),...invasion(13)]},
  {id:"s6-direction",stage:6,title:t("Von eigener Stärke aus","Playing from your strength"),minutes:3,steps:[
    task("direction",13,[...SAFE_GROUP,w(5,5)],"black",[p(4,5),p(4,6)],t("Deine sichere Gruppe steht links. Drücke Weiß von dieser Seite weg, statt einen isolierten Angreifer rechts zu setzen.","Your secure group is on the left. Push White away from that side instead of placing an isolated attacker on the right."),t("Die Angriffsrichtung nutzt deine vorhandene Stärke. Die Umgebung entscheidet, welche Seite einen Zug unterstützt.","This attacking direction uses your existing strength. The surroundings determine which side supports a move."),t("Links steht deine sichere Gruppe; rechts wäre dein neuer Stein ohne Unterstützung.","Your secure group is on the left; a new stone on the right would have no support.")),rescue(13),
  ]},
  {id:"s6-whole-board",stage:6,title:t("Das ganze Brett prüfen","Checking the whole board"),minutes:3,steps:[tenuki(13),rescue(13)]},
  {id:"s6-commented-game",stage:6,title:t("Eine 13×13-Partie durchspielen","Walk through a 13×13 game"),minutes:6,steps:commentedGame(13)},
  {id:"s6-first-game",stage:6,title:t("Deine erste 13×13-Partie","Your first 13×13 game"),minutes:15,challenge:true,steps:[{id:"game",kind:"beginner-game",gameSize:13,body:t("Spiele eine vollständige 13×13-Partie. Der Beginner Bot rechnet wie auf 9×9 lokal auf deinem Gerät.","Play a full 13×13 game. As on 9×9, the Beginner Bot calculates locally on your device."),task:t("Beende durch zwei Pässe und vereinbarte Wertung. Ein Sieg ist nicht erforderlich.","Finish with two passes and agreed scoring. A win is not required.")}]},
];
