ext {
    junitVersion = project.hasProperty('junitVersion') ? rootProject.ext.junitVersion : '4.13.2'
}

buildscript {
    repositories { google(); mavenCentral() }
    dependencies { classpath 'com.android.tools.build:gradle:8.13.0' }
}

apply plugin: 'com.android.library'

android {
    namespace = "com.gostone.katago"
    compileSdk = project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 36
    defaultConfig { minSdkVersion 24 }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

repositories { google(); mavenCentral() }

dependencies {
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
}
